- name: Demo on variable usage
  hosts: all
  vars:  
    URL: play.google.com
  tasks:
    - name: Printing the variable
      ansible.builtin.debug:
        msg: Value of the URL is {{URL}}

    - name: Printing the unknow variable
      ansible.builtin.debug:
        msg: Value of the xyz is {{XYZ}}